# This rule is not used by the project rbac-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over rbac-controller.io.rbaccontroller.ggh41th.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rbac-controller
    app.kubernetes.io/managed-by: kustomize
  name: rbacrule-admin-role
rules:
- apiGroups:
  - rbac-controller.io.rbaccontroller.ggh41th.io
  resources:
  - rbacrules
  verbs:
  - '*'
- apiGroups:
  - rbac-controller.io.rbaccontroller.ggh41th.io
  resources:
  - rbacrules/status
  verbs:
  - get
